// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	messages "github.com/CastyLab/grpc.proto/messages"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateStateRequest struct {
	State                messages.PERSONAL_STATE `protobuf:"varint,1,opt,name=state,proto3,enum=messages.PERSONAL_STATE" json:"state,omitempty"`
	AuthRequest          *AuthenticateRequest    `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateStateRequest) Reset()         { *m = UpdateStateRequest{} }
func (m *UpdateStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStateRequest) ProtoMessage()    {}
func (*UpdateStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{0}
}

func (m *UpdateStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStateRequest.Unmarshal(m, b)
}
func (m *UpdateStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStateRequest.Merge(m, src)
}
func (m *UpdateStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStateRequest.Size(m)
}
func (m *UpdateStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStateRequest proto.InternalMessageInfo

func (m *UpdateStateRequest) GetState() messages.PERSONAL_STATE {
	if m != nil {
		return m.State
	}
	return messages.PERSONAL_STATE_OFFLINE
}

func (m *UpdateStateRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type UpdateActivityRequest struct {
	Activity             *messages.Activity   `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateActivityRequest) Reset()         { *m = UpdateActivityRequest{} }
func (m *UpdateActivityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateActivityRequest) ProtoMessage()    {}
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{1}
}

func (m *UpdateActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateActivityRequest.Unmarshal(m, b)
}
func (m *UpdateActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateActivityRequest.Marshal(b, m, deterministic)
}
func (m *UpdateActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateActivityRequest.Merge(m, src)
}
func (m *UpdateActivityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateActivityRequest.Size(m)
}
func (m *UpdateActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateActivityRequest proto.InternalMessageInfo

func (m *UpdateActivityRequest) GetActivity() *messages.Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

func (m *UpdateActivityRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type FriendRequest struct {
	FriendId             string               `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{2}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetFriendId() string {
	if m != nil {
		return m.FriendId
	}
	return ""
}

func (m *FriendRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type CreateUserRequest struct {
	User                 *messages.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *messages.User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetFriendRequest struct {
	User                 *messages.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetFriendRequest) Reset()         { *m = GetFriendRequest{} }
func (m *GetFriendRequest) String() string { return proto.CompactTextString(m) }
func (*GetFriendRequest) ProtoMessage()    {}
func (*GetFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{4}
}

func (m *GetFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendRequest.Unmarshal(m, b)
}
func (m *GetFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendRequest.Marshal(b, m, deterministic)
}
func (m *GetFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendRequest.Merge(m, src)
}
func (m *GetFriendRequest) XXX_Size() int {
	return xxx_messageInfo_GetFriendRequest.Size(m)
}
func (m *GetFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendRequest proto.InternalMessageInfo

func (m *GetFriendRequest) GetUser() *messages.User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserResponse struct {
	Code                 int64          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *messages.User `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{5}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserResponse) GetResult() *messages.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type FriendsResponse struct {
	Code                 int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*messages.User `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FriendsResponse) Reset()         { *m = FriendsResponse{} }
func (m *FriendsResponse) String() string { return proto.CompactTextString(m) }
func (*FriendsResponse) ProtoMessage()    {}
func (*FriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{6}
}

func (m *FriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendsResponse.Unmarshal(m, b)
}
func (m *FriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendsResponse.Marshal(b, m, deterministic)
}
func (m *FriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendsResponse.Merge(m, src)
}
func (m *FriendsResponse) XXX_Size() int {
	return xxx_messageInfo_FriendsResponse.Size(m)
}
func (m *FriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FriendsResponse proto.InternalMessageInfo

func (m *FriendsResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FriendsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FriendsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FriendsResponse) GetResult() []*messages.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type FriendResponse struct {
	Code                 int64          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *messages.User `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FriendResponse) Reset()         { *m = FriendResponse{} }
func (m *FriendResponse) String() string { return proto.CompactTextString(m) }
func (*FriendResponse) ProtoMessage()    {}
func (*FriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{7}
}

func (m *FriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendResponse.Unmarshal(m, b)
}
func (m *FriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendResponse.Marshal(b, m, deterministic)
}
func (m *FriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendResponse.Merge(m, src)
}
func (m *FriendResponse) XXX_Size() int {
	return xxx_messageInfo_FriendResponse.Size(m)
}
func (m *FriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FriendResponse proto.InternalMessageInfo

func (m *FriendResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FriendResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *FriendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FriendResponse) GetResult() *messages.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateNotificationRequest struct {
	Notification         *messages.Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	AuthRequest          *AuthenticateRequest   `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateNotificationRequest) Reset()         { *m = CreateNotificationRequest{} }
func (m *CreateNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationRequest) ProtoMessage()    {}
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{8}
}

func (m *CreateNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationRequest.Unmarshal(m, b)
}
func (m *CreateNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationRequest.Merge(m, src)
}
func (m *CreateNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationRequest.Size(m)
}
func (m *CreateNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationRequest proto.InternalMessageInfo

func (m *CreateNotificationRequest) GetNotification() *messages.Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *CreateNotificationRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type NotificationResponse struct {
	Code                 int64                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string                   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UnreadCount          int64                    `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Result               []*messages.Notification `protobuf:"bytes,5,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NotificationResponse) Reset()         { *m = NotificationResponse{} }
func (m *NotificationResponse) String() string { return proto.CompactTextString(m) }
func (*NotificationResponse) ProtoMessage()    {}
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{9}
}

func (m *NotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationResponse.Unmarshal(m, b)
}
func (m *NotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationResponse.Marshal(b, m, deterministic)
}
func (m *NotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationResponse.Merge(m, src)
}
func (m *NotificationResponse) XXX_Size() int {
	return xxx_messageInfo_NotificationResponse.Size(m)
}
func (m *NotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationResponse proto.InternalMessageInfo

func (m *NotificationResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NotificationResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *NotificationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NotificationResponse) GetUnreadCount() int64 {
	if m != nil {
		return m.UnreadCount
	}
	return 0
}

func (m *NotificationResponse) GetResult() []*messages.Notification {
	if m != nil {
		return m.Result
	}
	return nil
}

type SearchUserRequest struct {
	Keyword              string               `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchUserRequest) Reset()         { *m = SearchUserRequest{} }
func (m *SearchUserRequest) String() string { return proto.CompactTextString(m) }
func (*SearchUserRequest) ProtoMessage()    {}
func (*SearchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{10}
}

func (m *SearchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserRequest.Unmarshal(m, b)
}
func (m *SearchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserRequest.Marshal(b, m, deterministic)
}
func (m *SearchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserRequest.Merge(m, src)
}
func (m *SearchUserRequest) XXX_Size() int {
	return xxx_messageInfo_SearchUserRequest.Size(m)
}
func (m *SearchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserRequest proto.InternalMessageInfo

func (m *SearchUserRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchUserRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type SearchUserResponse struct {
	Code                 int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*messages.User `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchUserResponse) Reset()         { *m = SearchUserResponse{} }
func (m *SearchUserResponse) String() string { return proto.CompactTextString(m) }
func (*SearchUserResponse) ProtoMessage()    {}
func (*SearchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{11}
}

func (m *SearchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUserResponse.Unmarshal(m, b)
}
func (m *SearchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUserResponse.Marshal(b, m, deterministic)
}
func (m *SearchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUserResponse.Merge(m, src)
}
func (m *SearchUserResponse) XXX_Size() int {
	return xxx_messageInfo_SearchUserResponse.Size(m)
}
func (m *SearchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUserResponse proto.InternalMessageInfo

func (m *SearchUserResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SearchUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SearchUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SearchUserResponse) GetResult() []*messages.User {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateStateRequest)(nil), "proto.UpdateStateRequest")
	proto.RegisterType((*UpdateActivityRequest)(nil), "proto.UpdateActivityRequest")
	proto.RegisterType((*FriendRequest)(nil), "proto.FriendRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
	proto.RegisterType((*GetFriendRequest)(nil), "proto.GetFriendRequest")
	proto.RegisterType((*GetUserResponse)(nil), "proto.GetUserResponse")
	proto.RegisterType((*FriendsResponse)(nil), "proto.FriendsResponse")
	proto.RegisterType((*FriendResponse)(nil), "proto.FriendResponse")
	proto.RegisterType((*CreateNotificationRequest)(nil), "proto.CreateNotificationRequest")
	proto.RegisterType((*NotificationResponse)(nil), "proto.NotificationResponse")
	proto.RegisterType((*SearchUserRequest)(nil), "proto.SearchUserRequest")
	proto.RegisterType((*SearchUserResponse)(nil), "proto.SearchUserResponse")
}

func init() {
	proto.RegisterFile("user.service.proto", fileDescriptor_1e7ed9320702f2c5)
}

var fileDescriptor_1e7ed9320702f2c5 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x49, 0x9b, 0x36, 0xd7, 0x25, 0xa5, 0xd3, 0x36, 0x72, 0x1c, 0x16, 0x21, 0x0b, 0xd4,
	0x95, 0x91, 0x82, 0xc4, 0xa3, 0x28, 0x82, 0xa8, 0x2a, 0x15, 0x02, 0xb5, 0xc8, 0x6e, 0xd7, 0x91,
	0x6b, 0xdf, 0x12, 0xab, 0xa9, 0x1d, 0x3c, 0xe3, 0xa0, 0x6e, 0x40, 0x02, 0x89, 0x4f, 0xe0, 0x33,
	0xe0, 0x17, 0x91, 0x67, 0xc6, 0xaf, 0xd8, 0x44, 0x95, 0x52, 0xd4, 0x55, 0x32, 0xf7, 0x79, 0xe6,
	0xdc, 0xb9, 0xc7, 0x40, 0x22, 0x8a, 0xa1, 0x41, 0x31, 0x9c, 0x79, 0x0e, 0x1a, 0xd3, 0x30, 0x60,
	0x01, 0x59, 0xe5, 0x3f, 0x3a, 0x9c, 0xdb, 0x54, 0x9a, 0x74, 0x62, 0x47, 0x6c, 0x5c, 0x0c, 0xd3,
	0xb7, 0xaf, 0x90, 0x52, 0xfb, 0x13, 0xd2, 0x27, 0xbc, 0x86, 0x30, 0x76, 0x52, 0xa3, 0x1f, 0x30,
	0xef, 0xc2, 0x73, 0x6c, 0xe6, 0x05, 0xbe, 0x70, 0xf6, 0x7e, 0x28, 0x40, 0xce, 0xa6, 0xae, 0xcd,
	0xd0, 0x62, 0x36, 0x43, 0x13, 0x3f, 0x47, 0x48, 0x19, 0x31, 0x60, 0x95, 0xc6, 0x67, 0x4d, 0xe9,
	0x2a, 0x7b, 0xcd, 0xbe, 0x66, 0x24, 0x35, 0x8c, 0x8f, 0x87, 0xa6, 0x75, 0x72, 0x3c, 0xfc, 0x30,
	0xb2, 0x4e, 0x87, 0xa7, 0x87, 0xa6, 0x08, 0x23, 0x03, 0xd8, 0x88, 0xe1, 0x8c, 0x42, 0x91, 0xaf,
	0xdd, 0xeb, 0x2a, 0x7b, 0x6a, 0x5f, 0x17, 0x4d, 0x8c, 0x61, 0xc4, 0xc6, 0xe8, 0xb3, 0xb8, 0x73,
	0xd2, 0xc1, 0x54, 0xe3, 0x78, 0x79, 0xe8, 0xfd, 0x54, 0x60, 0x57, 0xa0, 0x18, 0x3a, 0xcc, 0x9b,
	0x79, 0xec, 0x3a, 0x03, 0xb2, 0x6e, 0x4b, 0x13, 0xc7, 0xa2, 0xf6, 0x49, 0x86, 0x25, 0x0d, 0x4e,
	0x63, 0x96, 0x05, 0x72, 0x09, 0xf7, 0xdf, 0x86, 0x1e, 0xfa, 0x6e, 0xd2, 0xbf, 0x03, 0x8d, 0x0b,
	0x6e, 0x18, 0x79, 0x2e, 0x07, 0xd0, 0x30, 0xd7, 0x85, 0xe1, 0x9d, 0xbb, 0x6c, 0xb3, 0xe7, 0xb0,
	0x75, 0x10, 0xa2, 0xcd, 0xf0, 0x8c, 0x62, 0x98, 0x34, 0xec, 0xc1, 0x4a, 0x3c, 0x3b, 0x79, 0xd9,
	0x66, 0x76, 0x59, 0x1e, 0xc4, 0x7d, 0xbd, 0x67, 0xf0, 0xe0, 0x08, 0x59, 0x11, 0xe8, 0x4d, 0xf2,
	0xbe, 0xc1, 0xe6, 0x11, 0x32, 0xd1, 0x8d, 0x4e, 0x03, 0x9f, 0x22, 0x21, 0xb0, 0xe2, 0x04, 0xae,
	0x98, 0x73, 0xcd, 0xe4, 0xff, 0x49, 0x0b, 0xea, 0xf1, 0x54, 0x23, 0xca, 0x2f, 0xd4, 0x30, 0xe5,
	0x89, 0x68, 0xb0, 0x26, 0xab, 0x6a, 0x35, 0xee, 0x48, 0x8e, 0xe4, 0x31, 0xd4, 0x43, 0xa4, 0xd1,
	0x84, 0x69, 0x2b, 0x95, 0xed, 0xa5, 0x37, 0x06, 0x20, 0x50, 0xd3, 0xff, 0x08, 0xa0, 0xb6, 0x00,
	0xc0, 0x57, 0x68, 0x26, 0xb4, 0xdd, 0x09, 0x01, 0xbf, 0x14, 0x68, 0x8b, 0x99, 0x1f, 0xe7, 0x76,
	0x31, 0x99, 0xe1, 0x3e, 0x6c, 0xe4, 0x57, 0x54, 0xce, 0xb2, 0x95, 0xd5, 0x2a, 0x24, 0x15, 0x62,
	0x97, 0x7d, 0x8b, 0x7f, 0x14, 0xd8, 0x29, 0x42, 0xba, 0x55, 0x7e, 0x1e, 0xc1, 0x46, 0xe4, 0x87,
	0x68, 0xbb, 0x23, 0x27, 0x88, 0x7c, 0xc1, 0x52, 0xcd, 0x54, 0x85, 0xed, 0x20, 0x36, 0x11, 0x23,
	0xa5, 0x70, 0x95, 0x8f, 0xf0, 0x5f, 0xd7, 0x4e, 0xa8, 0x9c, 0xc0, 0x96, 0x85, 0x76, 0xe8, 0x8c,
	0xf3, 0xdb, 0xa3, 0xc1, 0xda, 0x25, 0x5e, 0x7f, 0x09, 0xc2, 0x64, 0x59, 0x93, 0xe3, 0xb2, 0xfc,
	0x7c, 0x57, 0x80, 0xe4, 0xdb, 0xdd, 0xc5, 0xeb, 0xed, 0xff, 0xae, 0x83, 0x1a, 0x1b, 0x2c, 0x21,
	0xfa, 0xe4, 0x25, 0xa8, 0x39, 0xed, 0x26, 0x6d, 0x79, 0x99, 0xb2, 0x9e, 0xeb, 0x9b, 0xd2, 0x95,
	0x02, 0x7f, 0x0d, 0xcd, 0xa2, 0xe0, 0x92, 0x87, 0x85, 0xec, 0x39, 0x1d, 0x2e, 0x17, 0x18, 0x40,
	0xd3, 0xc4, 0xab, 0x60, 0x96, 0x15, 0x58, 0xc0, 0x65, 0x55, 0xfa, 0x9a, 0x94, 0xa2, 0x85, 0x79,
	0x2d, 0xe9, 0x9b, 0x97, 0xad, 0x01, 0xd4, 0xc5, 0x34, 0x88, 0x26, 0x23, 0x4a, 0x6f, 0x41, 0x6f,
	0x57, 0x78, 0x64, 0xfa, 0x2b, 0x80, 0x4c, 0x79, 0xd3, 0x12, 0x25, 0x31, 0xd6, 0xb7, 0x73, 0xd0,
	0xd2, 0xe4, 0x17, 0xd0, 0x48, 0xd5, 0x97, 0xec, 0xc8, 0x88, 0x82, 0x18, 0xeb, 0xbb, 0x73, 0x56,
	0x99, 0xb9, 0x1f, 0x3f, 0x59, 0xdf, 0x2d, 0x0a, 0x77, 0x75, 0x85, 0x12, 0x61, 0x6f, 0x00, 0xd2,
	0xae, 0xf4, 0x46, 0x9c, 0xcd, 0x2b, 0xed, 0x7b, 0xfe, 0xd5, 0xc8, 0xef, 0xd2, 0xe2, 0x3a, 0x1d,
	0xe9, 0xab, 0x94, 0x05, 0x0b, 0x48, 0x59, 0xc7, 0x48, 0xb7, 0xc0, 0x64, 0x85, 0xc4, 0x2d, 0x2e,
	0x7a, 0x02, 0x3b, 0x26, 0xda, 0xee, 0x70, 0x32, 0xb9, 0x1d, 0x94, 0xe7, 0x75, 0xee, 0x7b, 0xfa,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x75, 0xd8, 0x48, 0xab, 0x53, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// User Profile
	UpdateState(ctx context.Context, in *UpdateStateRequest, opts ...grpc.CallOption) (*Response, error)
	UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveActivity(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Response, error)
	GetUser(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// FriendZone
	GetFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error)
	SendFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*Response, error)
	GetFriends(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*FriendsResponse, error)
	// Notifications
	GetNotifications(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
	ReadAllNotifications(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*NotificationResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UpdateState(ctx context.Context, in *UpdateStateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateActivity(ctx context.Context, in *UpdateActivityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveActivity(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.UserService/RemoveActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Search(ctx context.Context, in *SearchUserRequest, opts ...grpc.CallOption) (*SearchUserResponse, error) {
	out := new(SearchUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFriend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*FriendResponse, error) {
	out := new(FriendResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendFriendRequest(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.UserService/SendFriendRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetFriends(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*FriendsResponse, error) {
	out := new(FriendsResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetNotifications(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateNotification(ctx context.Context, in *CreateNotificationRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadAllNotifications(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/ReadAllNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// User Profile
	UpdateState(context.Context, *UpdateStateRequest) (*Response, error)
	UpdateActivity(context.Context, *UpdateActivityRequest) (*Response, error)
	RemoveActivity(context.Context, *AuthenticateRequest) (*Response, error)
	GetUser(context.Context, *AuthenticateRequest) (*GetUserResponse, error)
	Search(context.Context, *SearchUserRequest) (*SearchUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*AuthResponse, error)
	// FriendZone
	GetFriend(context.Context, *FriendRequest) (*FriendResponse, error)
	SendFriendRequest(context.Context, *FriendRequest) (*Response, error)
	GetFriends(context.Context, *AuthenticateRequest) (*FriendsResponse, error)
	// Notifications
	GetNotifications(context.Context, *AuthenticateRequest) (*NotificationResponse, error)
	CreateNotification(context.Context, *CreateNotificationRequest) (*NotificationResponse, error)
	ReadAllNotifications(context.Context, *AuthenticateRequest) (*NotificationResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) UpdateState(ctx context.Context, req *UpdateStateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateState not implemented")
}
func (*UnimplementedUserServiceServer) UpdateActivity(ctx context.Context, req *UpdateActivityRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (*UnimplementedUserServiceServer) RemoveActivity(ctx context.Context, req *AuthenticateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveActivity not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *AuthenticateRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) Search(ctx context.Context, req *SearchUserRequest) (*SearchUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) GetFriend(ctx context.Context, req *FriendRequest) (*FriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriend not implemented")
}
func (*UnimplementedUserServiceServer) SendFriendRequest(ctx context.Context, req *FriendRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (*UnimplementedUserServiceServer) GetFriends(ctx context.Context, req *AuthenticateRequest) (*FriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (*UnimplementedUserServiceServer) GetNotifications(ctx context.Context, req *AuthenticateRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (*UnimplementedUserServiceServer) CreateNotification(ctx context.Context, req *CreateNotificationRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotification not implemented")
}
func (*UnimplementedUserServiceServer) ReadAllNotifications(ctx context.Context, req *AuthenticateRequest) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllNotifications not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UpdateState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateState(ctx, req.(*UpdateStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateActivity(ctx, req.(*UpdateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/RemoveActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveActivity(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Search(ctx, req.(*SearchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFriend(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/SendFriendRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendFriendRequest(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetFriends(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetNotifications(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateNotification(ctx, req.(*CreateNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadAllNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadAllNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/ReadAllNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadAllNotifications(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateState",
			Handler:    _UserService_UpdateState_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _UserService_UpdateActivity_Handler,
		},
		{
			MethodName: "RemoveActivity",
			Handler:    _UserService_RemoveActivity_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _UserService_Search_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetFriend",
			Handler:    _UserService_GetFriend_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _UserService_SendFriendRequest_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _UserService_GetFriends_Handler,
		},
		{
			MethodName: "GetNotifications",
			Handler:    _UserService_GetNotifications_Handler,
		},
		{
			MethodName: "CreateNotification",
			Handler:    _UserService_CreateNotification_Handler,
		},
		{
			MethodName: "ReadAllNotifications",
			Handler:    _UserService_ReadAllNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.service.proto",
}
