// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender               *User                `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Reciever             *User                `protobuf:"bytes,4,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Edited               bool                 `protobuf:"varint,5,opt,name=edited,proto3" json:"edited,omitempty"`
	Deleted              bool                 `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1075520738a77fe1, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetSender() *User {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetReciever() *User {
	if m != nil {
		return m.Reciever
	}
	return nil
}

func (m *Message) GetEdited() bool {
	if m != nil {
		return m.Edited
	}
	return false
}

func (m *Message) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Message) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Message) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Message) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type GetMessagesRequest struct {
	ReceiverId           string               `protobuf:"bytes,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1075520738a77fe1, []int{1}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *GetMessagesRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type GetMessagesResponse struct {
	Code                 int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*Message `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1075520738a77fe1, []int{2}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetMessagesResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetMessagesResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetMessagesResponse) GetResult() []*Message {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateMessageRequest struct {
	RecieverId           string               `protobuf:"bytes,1,opt,name=reciever_id,json=recieverId,proto3" json:"reciever_id,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,3,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1075520738a77fe1, []int{3}
}

func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (m *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(m, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetRecieverId() string {
	if m != nil {
		return m.RecieverId
	}
	return ""
}

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateMessageRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type CreateMessageResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Result               *Message `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageResponse) Reset()         { *m = CreateMessageResponse{} }
func (m *CreateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMessageResponse) ProtoMessage()    {}
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1075520738a77fe1, []int{4}
}

func (m *CreateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageResponse.Unmarshal(m, b)
}
func (m *CreateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageResponse.Marshal(b, m, deterministic)
}
func (m *CreateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageResponse.Merge(m, src)
}
func (m *CreateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMessageResponse.Size(m)
}
func (m *CreateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageResponse proto.InternalMessageInfo

func (m *CreateMessageResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateMessageResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *CreateMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateMessageResponse) GetResult() *Message {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*GetMessagesRequest)(nil), "proto.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "proto.GetMessagesResponse")
	proto.RegisterType((*CreateMessageRequest)(nil), "proto.CreateMessageRequest")
	proto.RegisterType((*CreateMessageResponse)(nil), "proto.CreateMessageResponse")
}

func init() {
	proto.RegisterFile("grpc.message.proto", fileDescriptor_1075520738a77fe1)
}

var fileDescriptor_1075520738a77fe1 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xd6, 0xc6, 0xad, 0x9b, 0x8c, 0xa1, 0x91, 0x96, 0x1f, 0x19, 0x83, 0xd4, 0x28, 0x48, 0x90,
	0x93, 0x2b, 0x85, 0x13, 0x07, 0x0e, 0x11, 0x87, 0x52, 0x24, 0x2e, 0x0b, 0x9c, 0x23, 0xc7, 0x3b,
	0xa4, 0x96, 0x12, 0xdb, 0xec, 0x8e, 0xf3, 0x02, 0x88, 0x3b, 0x6f, 0xc1, 0x8b, 0xf1, 0x20, 0x68,
	0xd7, 0xb3, 0x95, 0xd2, 0x06, 0x2a, 0x0e, 0x9c, 0x92, 0x99, 0x6f, 0xbe, 0x99, 0x9d, 0xef, 0x1b,
	0x83, 0x5c, 0x9b, 0xb6, 0xcc, 0xb7, 0x68, 0x6d, 0xb1, 0xc6, 0xbc, 0x35, 0x0d, 0x35, 0xf2, 0xd8,
	0xff, 0x64, 0x63, 0x0f, 0xad, 0x0a, 0xcb, 0x79, 0x4e, 0x74, 0x16, 0x0d, 0x27, 0xce, 0xd6, 0x4d,
	0xb3, 0xde, 0xe0, 0xb9, 0x8f, 0x56, 0xdd, 0x97, 0x73, 0xaa, 0xb6, 0x68, 0xa9, 0xd8, 0xb6, 0x7d,
	0xc1, 0xf4, 0xd7, 0x00, 0x4e, 0x3e, 0xf4, 0xbd, 0xe5, 0x29, 0x0c, 0x2a, 0x9d, 0x8a, 0x89, 0x98,
	0x8d, 0xd4, 0xa0, 0xd2, 0x32, 0x85, 0x93, 0xb2, 0xa9, 0x09, 0x6b, 0x4a, 0x07, 0x3e, 0x19, 0x42,
	0xf9, 0x1c, 0x62, 0x8b, 0xb5, 0x46, 0x93, 0x46, 0x13, 0x31, 0x4b, 0xe6, 0x49, 0xdf, 0x2d, 0xff,
	0x6c, 0xd1, 0x28, 0x86, 0xe4, 0x4b, 0x18, 0x1a, 0x2c, 0x2b, 0xdc, 0xa1, 0x49, 0x8f, 0x6e, 0x97,
	0x5d, 0x83, 0xf2, 0x31, 0xc4, 0xa8, 0x2b, 0x42, 0x9d, 0x1e, 0x4f, 0xc4, 0x6c, 0xa8, 0x38, 0x72,
	0xf3, 0x35, 0x6e, 0xd0, 0x01, 0xb1, 0x07, 0x42, 0x28, 0x5f, 0x03, 0x94, 0x06, 0x0b, 0x42, 0xbd,
	0x2c, 0x28, 0x3d, 0xf1, 0xcd, 0xb3, 0xbc, 0xdf, 0x35, 0x0f, 0xbb, 0xe6, 0x9f, 0xc2, 0xae, 0x6a,
	0xc4, 0xd5, 0x0b, 0x72, 0xd4, 0xae, 0xd5, 0x81, 0x3a, 0xbc, 0x9b, 0xca, 0xd5, 0x3d, 0x95, 0x1f,
	0xe0, 0xa8, 0xa3, 0xbb, 0xa9, 0x5c, 0xbd, 0xa0, 0x29, 0x81, 0xbc, 0x40, 0x62, 0xa1, 0xad, 0xc2,
	0xaf, 0x1d, 0x5a, 0x92, 0x67, 0x90, 0x18, 0x2c, 0xb1, 0xda, 0xa1, 0x59, 0x5e, 0x2b, 0x0f, 0x21,
	0x75, 0xa9, 0xe5, 0x1b, 0xb8, 0x57, 0x74, 0x74, 0xb5, 0x34, 0x3d, 0xc1, 0xdb, 0xe0, 0x66, 0xf6,
	0x32, 0x2e, 0x3a, 0xba, 0xc2, 0x9a, 0xaa, 0xb2, 0x20, 0xe4, 0x96, 0x2a, 0x71, 0xf5, 0x1c, 0x4c,
	0xbf, 0x09, 0x78, 0xb0, 0x37, 0xd6, 0xb6, 0x4d, 0x6d, 0x51, 0x4a, 0x38, 0x2a, 0x1b, 0x8d, 0x7e,
	0x60, 0xa4, 0xfc, 0x7f, 0x67, 0x82, 0xa5, 0x82, 0x3a, 0xcb, 0x5e, 0x73, 0xe4, 0x4c, 0xe0, 0xdb,
	0xf3, 0x26, 0x8e, 0x54, 0x08, 0xe5, 0x0b, 0x88, 0x0d, 0xda, 0x6e, 0x43, 0x69, 0x34, 0x89, 0x66,
	0xc9, 0xfc, 0x94, 0x9f, 0xc5, 0xe3, 0x14, 0xa3, 0xd3, 0x1f, 0x02, 0x1e, 0xbe, 0xf5, 0xfa, 0x07,
	0x64, 0x6f, 0x7d, 0x7f, 0x03, 0xfb, 0xeb, 0xfb, 0xd4, 0xe5, 0xdf, 0x0e, 0xf0, 0xa6, 0x30, 0xd1,
	0xbf, 0x09, 0xf3, 0x5d, 0xc0, 0xa3, 0x1b, 0x4f, 0xfa, 0x6f, 0xd2, 0x88, 0x3f, 0x4b, 0x33, 0xff,
	0x29, 0x60, 0x1c, 0xdc, 0xf9, 0x88, 0x66, 0x57, 0x95, 0x28, 0xdf, 0xc1, 0xf8, 0x02, 0xc9, 0x7d,
	0x22, 0x01, 0x91, 0x4f, 0x98, 0x7e, 0xfb, 0x84, 0xb2, 0xec, 0x10, 0xc4, 0xbb, 0xbc, 0x87, 0xfb,
	0x7b, 0x4b, 0xca, 0xa7, 0x5c, 0x7c, 0xc8, 0x8d, 0xec, 0xd9, 0x61, 0xb0, 0xef, 0xb5, 0x8a, 0x3d,
	0xf8, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x16, 0x58, 0x41, 0x8e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessagesServiceClient is the client API for MessagesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagesServiceClient interface {
	GetUserMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
}

type messagesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagesServiceClient(cc grpc.ClientConnInterface) MessagesServiceClient {
	return &messagesServiceClient{cc}
}

func (c *messagesServiceClient) GetUserMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/proto.MessagesService/GetUserMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagesServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.MessagesService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagesServiceServer is the server API for MessagesService service.
type MessagesServiceServer interface {
	GetUserMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
}

// UnimplementedMessagesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessagesServiceServer struct {
}

func (*UnimplementedMessagesServiceServer) GetUserMessages(ctx context.Context, req *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMessages not implemented")
}
func (*UnimplementedMessagesServiceServer) CreateMessage(ctx context.Context, req *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}

func RegisterMessagesServiceServer(s *grpc.Server, srv MessagesServiceServer) {
	s.RegisterService(&_MessagesService_serviceDesc, srv)
}

func _MessagesService_GetUserMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).GetUserMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessagesService/GetUserMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).GetUserMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagesService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MessagesService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessagesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MessagesService",
	HandlerType: (*MessagesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserMessages",
			Handler:    _MessagesService_GetUserMessages_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _MessagesService_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.message.proto",
}
