// Code generated by protoc-gen-go. DO NOT EDIT.
// source: theater.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PRIVACY int32

const (
	PRIVACY_PRIVATE  PRIVACY = 0
	PRIVACY_EVERYONE PRIVACY = 1
	PRIVACY_PUBLIC   PRIVACY = 2
)

var PRIVACY_name = map[int32]string{
	0: "PRIVATE",
	1: "EVERYONE",
	2: "PUBLIC",
}

var PRIVACY_value = map[string]int32{
	"PRIVATE":  0,
	"EVERYONE": 1,
	"PUBLIC":   2,
}

func (x PRIVACY) String() string {
	return proto.EnumName(PRIVACY_name, int32(x))
}

func (PRIVACY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{0}
}

type MovieType int32

const (
	MovieType_UNKNOWN    MovieType = 0
	MovieType_YOUTUBE    MovieType = 1
	MovieType_URI        MovieType = 2
	MovieType_PIRATE_BAY MovieType = 3
	MovieType_LOCAL_PATH MovieType = 4
)

var MovieType_name = map[int32]string{
	0: "UNKNOWN",
	1: "YOUTUBE",
	2: "URI",
	3: "PIRATE_BAY",
	4: "LOCAL_PATH",
}

var MovieType_value = map[string]int32{
	"UNKNOWN":    0,
	"YOUTUBE":    1,
	"URI":        2,
	"PIRATE_BAY": 3,
	"LOCAL_PATH": 4,
}

func (x MovieType) String() string {
	return proto.EnumName(MovieType_name, int32(x))
}

func (MovieType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{1}
}

type Subtitle struct {
	Lang                 string   `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subtitle) Reset()         { *m = Subtitle{} }
func (m *Subtitle) String() string { return proto.CompactTextString(m) }
func (*Subtitle) ProtoMessage()    {}
func (*Subtitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{0}
}

func (m *Subtitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subtitle.Unmarshal(m, b)
}
func (m *Subtitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subtitle.Marshal(b, m, deterministic)
}
func (m *Subtitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subtitle.Merge(m, src)
}
func (m *Subtitle) XXX_Size() int {
	return xxx_messageInfo_Subtitle.Size(m)
}
func (m *Subtitle) XXX_DiscardUnknown() {
	xxx_messageInfo_Subtitle.DiscardUnknown(m)
}

var xxx_messageInfo_Subtitle proto.InternalMessageInfo

func (m *Subtitle) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Subtitle) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type Movie struct {
	Type                 MovieType   `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MovieType" json:"type,omitempty"`
	Uri                  string      `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Poster               string      `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	Size                 int64       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Length               int64       `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	LastPlayedTime       int64       `protobuf:"varint,6,opt,name=last_played_time,json=lastPlayedTime,proto3" json:"last_played_time,omitempty"`
	Subtitles            []*Subtitle `protobuf:"bytes,7,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{1}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetType() MovieType {
	if m != nil {
		return m.Type
	}
	return MovieType_UNKNOWN
}

func (m *Movie) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Movie) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *Movie) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Movie) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Movie) GetLastPlayedTime() int64 {
	if m != nil {
		return m.LastPlayedTime
	}
	return 0
}

func (m *Movie) GetSubtitles() []*Subtitle {
	if m != nil {
		return m.Subtitles
	}
	return nil
}

type Theater struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Hash                 string               `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Privacy              PRIVACY              `protobuf:"varint,4,opt,name=privacy,proto3,enum=proto.PRIVACY" json:"privacy,omitempty"`
	VideoPlayerAccess    PRIVACY              `protobuf:"varint,5,opt,name=video_player_access,json=videoPlayerAccess,proto3,enum=proto.PRIVACY" json:"video_player_access,omitempty"`
	UserId               string               `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *User                `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Movie                *Movie               `protobuf:"bytes,8,opt,name=movie,proto3" json:"movie,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Theater) Reset()         { *m = Theater{} }
func (m *Theater) String() string { return proto.CompactTextString(m) }
func (*Theater) ProtoMessage()    {}
func (*Theater) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{2}
}

func (m *Theater) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Theater.Unmarshal(m, b)
}
func (m *Theater) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Theater.Marshal(b, m, deterministic)
}
func (m *Theater) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Theater.Merge(m, src)
}
func (m *Theater) XXX_Size() int {
	return xxx_messageInfo_Theater.Size(m)
}
func (m *Theater) XXX_DiscardUnknown() {
	xxx_messageInfo_Theater.DiscardUnknown(m)
}

var xxx_messageInfo_Theater proto.InternalMessageInfo

func (m *Theater) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Theater) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Theater) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Theater) GetPrivacy() PRIVACY {
	if m != nil {
		return m.Privacy
	}
	return PRIVACY_PRIVATE
}

func (m *Theater) GetVideoPlayerAccess() PRIVACY {
	if m != nil {
		return m.VideoPlayerAccess
	}
	return PRIVACY_PRIVATE
}

func (m *Theater) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Theater) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Theater) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *Theater) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Theater) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetAllUserTheatersRequest struct {
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAllUserTheatersRequest) Reset()         { *m = GetAllUserTheatersRequest{} }
func (m *GetAllUserTheatersRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllUserTheatersRequest) ProtoMessage()    {}
func (*GetAllUserTheatersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{3}
}

func (m *GetAllUserTheatersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserTheatersRequest.Unmarshal(m, b)
}
func (m *GetAllUserTheatersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserTheatersRequest.Marshal(b, m, deterministic)
}
func (m *GetAllUserTheatersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserTheatersRequest.Merge(m, src)
}
func (m *GetAllUserTheatersRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllUserTheatersRequest.Size(m)
}
func (m *GetAllUserTheatersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserTheatersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserTheatersRequest proto.InternalMessageInfo

func (m *GetAllUserTheatersRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type CreateTheaterRequest struct {
	Theater              *Theater             `protobuf:"bytes,1,opt,name=theater,proto3" json:"theater,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTheaterRequest) Reset()         { *m = CreateTheaterRequest{} }
func (m *CreateTheaterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTheaterRequest) ProtoMessage()    {}
func (*CreateTheaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{4}
}

func (m *CreateTheaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTheaterRequest.Unmarshal(m, b)
}
func (m *CreateTheaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTheaterRequest.Marshal(b, m, deterministic)
}
func (m *CreateTheaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTheaterRequest.Merge(m, src)
}
func (m *CreateTheaterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTheaterRequest.Size(m)
}
func (m *CreateTheaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTheaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTheaterRequest proto.InternalMessageInfo

func (m *CreateTheaterRequest) GetTheater() *Theater {
	if m != nil {
		return m.Theater
	}
	return nil
}

func (m *CreateTheaterRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type TheaterAuthRequest struct {
	Theater              *Theater             `protobuf:"bytes,1,opt,name=theater,proto3" json:"theater,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TheaterAuthRequest) Reset()         { *m = TheaterAuthRequest{} }
func (m *TheaterAuthRequest) String() string { return proto.CompactTextString(m) }
func (*TheaterAuthRequest) ProtoMessage()    {}
func (*TheaterAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{5}
}

func (m *TheaterAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterAuthRequest.Unmarshal(m, b)
}
func (m *TheaterAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterAuthRequest.Marshal(b, m, deterministic)
}
func (m *TheaterAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterAuthRequest.Merge(m, src)
}
func (m *TheaterAuthRequest) XXX_Size() int {
	return xxx_messageInfo_TheaterAuthRequest.Size(m)
}
func (m *TheaterAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterAuthRequest proto.InternalMessageInfo

func (m *TheaterAuthRequest) GetTheater() *Theater {
	if m != nil {
		return m.Theater
	}
	return nil
}

func (m *TheaterAuthRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type UserTheatersResponse struct {
	Code                 int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*Theater `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserTheatersResponse) Reset()         { *m = UserTheatersResponse{} }
func (m *UserTheatersResponse) String() string { return proto.CompactTextString(m) }
func (*UserTheatersResponse) ProtoMessage()    {}
func (*UserTheatersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{6}
}

func (m *UserTheatersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTheatersResponse.Unmarshal(m, b)
}
func (m *UserTheatersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTheatersResponse.Marshal(b, m, deterministic)
}
func (m *UserTheatersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTheatersResponse.Merge(m, src)
}
func (m *UserTheatersResponse) XXX_Size() int {
	return xxx_messageInfo_UserTheatersResponse.Size(m)
}
func (m *UserTheatersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTheatersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTheatersResponse proto.InternalMessageInfo

func (m *UserTheatersResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserTheatersResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserTheatersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserTheatersResponse) GetResult() []*Theater {
	if m != nil {
		return m.Result
	}
	return nil
}

type UserTheaterResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *Theater `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTheaterResponse) Reset()         { *m = UserTheaterResponse{} }
func (m *UserTheaterResponse) String() string { return proto.CompactTextString(m) }
func (*UserTheaterResponse) ProtoMessage()    {}
func (*UserTheaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{7}
}

func (m *UserTheaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTheaterResponse.Unmarshal(m, b)
}
func (m *UserTheaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTheaterResponse.Marshal(b, m, deterministic)
}
func (m *UserTheaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTheaterResponse.Merge(m, src)
}
func (m *UserTheaterResponse) XXX_Size() int {
	return xxx_messageInfo_UserTheaterResponse.Size(m)
}
func (m *UserTheaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTheaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTheaterResponse proto.InternalMessageInfo

func (m *UserTheaterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserTheaterResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserTheaterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserTheaterResponse) GetResult() *Theater {
	if m != nil {
		return m.Result
	}
	return nil
}

type TheaterMembersResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*User  `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TheaterMembersResponse) Reset()         { *m = TheaterMembersResponse{} }
func (m *TheaterMembersResponse) String() string { return proto.CompactTextString(m) }
func (*TheaterMembersResponse) ProtoMessage()    {}
func (*TheaterMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{8}
}

func (m *TheaterMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterMembersResponse.Unmarshal(m, b)
}
func (m *TheaterMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterMembersResponse.Marshal(b, m, deterministic)
}
func (m *TheaterMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterMembersResponse.Merge(m, src)
}
func (m *TheaterMembersResponse) XXX_Size() int {
	return xxx_messageInfo_TheaterMembersResponse.Size(m)
}
func (m *TheaterMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterMembersResponse proto.InternalMessageInfo

func (m *TheaterMembersResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TheaterMembersResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TheaterMembersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TheaterMembersResponse) GetResult() []*User {
	if m != nil {
		return m.Result
	}
	return nil
}

type AddOrRemoveMemberRequest struct {
	MemberId             string               `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	TheaterId            string               `protobuf:"bytes,2,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,3,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddOrRemoveMemberRequest) Reset()         { *m = AddOrRemoveMemberRequest{} }
func (m *AddOrRemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrRemoveMemberRequest) ProtoMessage()    {}
func (*AddOrRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{9}
}

func (m *AddOrRemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Unmarshal(m, b)
}
func (m *AddOrRemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddOrRemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrRemoveMemberRequest.Merge(m, src)
}
func (m *AddOrRemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Size(m)
}
func (m *AddOrRemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrRemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrRemoveMemberRequest proto.InternalMessageInfo

func (m *AddOrRemoveMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *AddOrRemoveMemberRequest) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *AddOrRemoveMemberRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type GetTheaterMembersRequest struct {
	TheaterId            string               `protobuf:"bytes,2,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,3,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTheaterMembersRequest) Reset()         { *m = GetTheaterMembersRequest{} }
func (m *GetTheaterMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTheaterMembersRequest) ProtoMessage()    {}
func (*GetTheaterMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{10}
}

func (m *GetTheaterMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTheaterMembersRequest.Unmarshal(m, b)
}
func (m *GetTheaterMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTheaterMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetTheaterMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTheaterMembersRequest.Merge(m, src)
}
func (m *GetTheaterMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTheaterMembersRequest.Size(m)
}
func (m *GetTheaterMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTheaterMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTheaterMembersRequest proto.InternalMessageInfo

func (m *GetTheaterMembersRequest) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *GetTheaterMembersRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type InviteFriendsTheaterRequest struct {
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	TheaterId            string               `protobuf:"bytes,2,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	FriendIds            []string             `protobuf:"bytes,3,rep,name=friend_ids,json=friendIds,proto3" json:"friend_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InviteFriendsTheaterRequest) Reset()         { *m = InviteFriendsTheaterRequest{} }
func (m *InviteFriendsTheaterRequest) String() string { return proto.CompactTextString(m) }
func (*InviteFriendsTheaterRequest) ProtoMessage()    {}
func (*InviteFriendsTheaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{11}
}

func (m *InviteFriendsTheaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteFriendsTheaterRequest.Unmarshal(m, b)
}
func (m *InviteFriendsTheaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteFriendsTheaterRequest.Marshal(b, m, deterministic)
}
func (m *InviteFriendsTheaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteFriendsTheaterRequest.Merge(m, src)
}
func (m *InviteFriendsTheaterRequest) XXX_Size() int {
	return xxx_messageInfo_InviteFriendsTheaterRequest.Size(m)
}
func (m *InviteFriendsTheaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteFriendsTheaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteFriendsTheaterRequest proto.InternalMessageInfo

func (m *InviteFriendsTheaterRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

func (m *InviteFriendsTheaterRequest) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *InviteFriendsTheaterRequest) GetFriendIds() []string {
	if m != nil {
		return m.FriendIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.PRIVACY", PRIVACY_name, PRIVACY_value)
	proto.RegisterEnum("proto.MovieType", MovieType_name, MovieType_value)
	proto.RegisterType((*Subtitle)(nil), "proto.Subtitle")
	proto.RegisterType((*Movie)(nil), "proto.Movie")
	proto.RegisterType((*Theater)(nil), "proto.Theater")
	proto.RegisterType((*GetAllUserTheatersRequest)(nil), "proto.GetAllUserTheatersRequest")
	proto.RegisterType((*CreateTheaterRequest)(nil), "proto.CreateTheaterRequest")
	proto.RegisterType((*TheaterAuthRequest)(nil), "proto.TheaterAuthRequest")
	proto.RegisterType((*UserTheatersResponse)(nil), "proto.UserTheatersResponse")
	proto.RegisterType((*UserTheaterResponse)(nil), "proto.UserTheaterResponse")
	proto.RegisterType((*TheaterMembersResponse)(nil), "proto.TheaterMembersResponse")
	proto.RegisterType((*AddOrRemoveMemberRequest)(nil), "proto.AddOrRemoveMemberRequest")
	proto.RegisterType((*GetTheaterMembersRequest)(nil), "proto.GetTheaterMembersRequest")
	proto.RegisterType((*InviteFriendsTheaterRequest)(nil), "proto.InviteFriendsTheaterRequest")
}

func init() {
	proto.RegisterFile("theater.proto", fileDescriptor_9ca216068025a679)
}

var fileDescriptor_9ca216068025a679 = []byte{
	// 956 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5b, 0x6f, 0xe3, 0x54,
	0x10, 0x5e, 0xc7, 0xb9, 0xd4, 0x93, 0x36, 0x6b, 0xce, 0x56, 0x8b, 0x37, 0x55, 0xd5, 0x28, 0x20,
	0x14, 0xad, 0x44, 0x16, 0x85, 0x17, 0x56, 0xa8, 0x08, 0xb7, 0x0a, 0xc5, 0xa2, 0x9b, 0x44, 0xde,
	0x64, 0x51, 0x79, 0xb1, 0x9c, 0x9c, 0xd3, 0xe4, 0x48, 0x4e, 0x6c, 0x7c, 0x8e, 0x23, 0x8a, 0x84,
	0x10, 0x82, 0xbf, 0xc0, 0x0b, 0xbf, 0x8d, 0x17, 0xfe, 0x09, 0x3a, 0x17, 0xa7, 0xb9, 0xd0, 0x5d,
	0xed, 0x42, 0x79, 0xca, 0x5c, 0xbe, 0x6f, 0xce, 0xcc, 0x78, 0x66, 0x02, 0x07, 0x7c, 0x46, 0x42,
	0x4e, 0xd2, 0x76, 0x92, 0xc6, 0x3c, 0x46, 0x25, 0xf9, 0x53, 0x87, 0x71, 0xc8, 0x48, 0x5b, 0xcb,
	0x19, 0xcb, 0xdd, 0xf5, 0x93, 0x69, 0x1c, 0x4f, 0x23, 0xf2, 0x4c, 0x6a, 0xe3, 0xec, 0xfa, 0x19,
	0xa7, 0x73, 0xc2, 0x78, 0x38, 0x4f, 0x14, 0xa0, 0xd9, 0x81, 0xbd, 0x97, 0xd9, 0x98, 0x53, 0x1e,
	0x11, 0x84, 0xa0, 0x18, 0x85, 0x8b, 0xa9, 0x63, 0x34, 0x8c, 0x96, 0xe5, 0x4b, 0x59, 0xd8, 0xae,
	0x69, 0x44, 0x9c, 0x82, 0xb2, 0x09, 0xb9, 0xf9, 0xa7, 0x01, 0xa5, 0x17, 0xf1, 0x92, 0x12, 0xf4,
	0x21, 0x14, 0xf9, 0x4d, 0x42, 0x24, 0xa3, 0xd6, 0xb1, 0x55, 0xcc, 0xb6, 0xf4, 0x0d, 0x6f, 0x12,
	0xe2, 0x4b, 0x2f, 0xb2, 0xc1, 0xcc, 0x52, 0xaa, 0x43, 0x08, 0x11, 0x3d, 0x86, 0x72, 0x12, 0x33,
	0x4e, 0x52, 0xc7, 0x94, 0x46, 0xad, 0x89, 0xd7, 0x18, 0xfd, 0x91, 0x38, 0xc5, 0x86, 0xd1, 0x32,
	0x7d, 0x29, 0x0b, 0x6c, 0x44, 0x16, 0x53, 0x3e, 0x73, 0x4a, 0xd2, 0xaa, 0x35, 0xd4, 0x02, 0x3b,
	0x0a, 0x19, 0x0f, 0x92, 0x28, 0xbc, 0x21, 0x38, 0x10, 0x85, 0x39, 0x65, 0x89, 0xa8, 0x09, 0xfb,
	0x40, 0x9a, 0x87, 0x74, 0x4e, 0xd0, 0xc7, 0x60, 0x31, 0x5d, 0x23, 0x73, 0x2a, 0x0d, 0xb3, 0x55,
	0xed, 0x3c, 0xd4, 0xa9, 0xe6, 0xb5, 0xfb, 0xb7, 0x88, 0xe6, 0x2f, 0x26, 0x54, 0x86, 0xaa, 0xc9,
	0xa8, 0x06, 0x05, 0x8a, 0x75, 0x43, 0x0a, 0x14, 0xa3, 0x43, 0x28, 0x49, 0x94, 0x2e, 0xa6, 0xb4,
	0x6a, 0xdc, 0x2c, 0x64, 0x33, 0x5d, 0x8c, 0x94, 0x51, 0x0b, 0x2a, 0x49, 0x4a, 0x97, 0xe1, 0xe4,
	0x46, 0x56, 0x53, 0xeb, 0xd4, 0xf4, 0x93, 0x03, 0xdf, 0x7b, 0xe5, 0x9e, 0x5f, 0xf9, 0xb9, 0x1b,
	0x7d, 0x01, 0x8f, 0x96, 0x14, 0x93, 0x58, 0x55, 0x92, 0x06, 0xe1, 0x64, 0x42, 0x18, 0x93, 0xd5,
	0xee, 0xb2, 0xde, 0x93, 0x50, 0x59, 0x5c, 0xea, 0x4a, 0x20, 0x7a, 0x1f, 0x2a, 0xe2, 0x8b, 0x07,
	0x14, 0xcb, 0xfa, 0x2d, 0xbf, 0x2c, 0x54, 0x0f, 0xa3, 0x13, 0x28, 0x0a, 0xc9, 0xa9, 0x34, 0x8c,
	0x56, 0xb5, 0x53, 0xd5, 0x91, 0x46, 0x8c, 0xa4, 0xbe, 0x74, 0xa0, 0x26, 0x94, 0xe6, 0xe2, 0x5b,
	0x39, 0x7b, 0x12, 0xb1, 0xbf, 0xfe, 0xfd, 0x7c, 0xe5, 0x42, 0xcf, 0x01, 0x26, 0xa9, 0x68, 0x06,
	0x0e, 0x42, 0xee, 0x58, 0x12, 0x58, 0x6f, 0xab, 0xb1, 0x6a, 0xe7, 0x63, 0xd5, 0x1e, 0xe6, 0x63,
	0xe5, 0x5b, 0x1a, 0xed, 0x72, 0x41, 0xcd, 0x12, 0x9c, 0x53, 0xe1, 0xcd, 0x54, 0x8d, 0x76, 0x79,
	0xf3, 0x3b, 0x78, 0x72, 0x41, 0xb8, 0x1b, 0x45, 0x22, 0x5b, 0xfd, 0x31, 0x98, 0x4f, 0xbe, 0xcf,
	0x08, 0xe3, 0xe8, 0x14, 0xf6, 0xc3, 0x8c, 0xcf, 0x82, 0x54, 0xe9, 0xf2, 0xf3, 0x88, 0xc8, 0x2a,
	0x7b, 0x37, 0xe3, 0x33, 0xb2, 0xe0, 0x74, 0x12, 0x72, 0xa2, 0x19, 0x7e, 0x55, 0xe0, 0xb5, 0xd2,
	0xfc, 0x19, 0x0e, 0xcf, 0x65, 0x8e, 0x3a, 0x6e, 0x1e, 0xb6, 0x05, 0x15, 0xbd, 0x5b, 0x3a, 0x62,
	0xde, 0xfb, 0x1c, 0x97, 0xbb, 0x77, 0x12, 0x28, 0xbc, 0x5d, 0x02, 0x3f, 0x01, 0xd2, 0x21, 0xdd,
	0x5b, 0xeb, 0xff, 0xf7, 0xfc, 0x6f, 0x06, 0x1c, 0x6e, 0xb6, 0x95, 0x25, 0xf1, 0x82, 0xc9, 0x31,
	0x9e, 0xc4, 0x58, 0x6d, 0xb3, 0xe9, 0x4b, 0x59, 0x6c, 0x1f, 0xe3, 0x21, 0xcf, 0x98, 0x9e, 0x78,
	0xad, 0x21, 0x07, 0x2a, 0x73, 0xc2, 0x58, 0x38, 0x25, 0x7a, 0xea, 0x73, 0x15, 0x7d, 0x04, 0xe5,
	0x94, 0xb0, 0x2c, 0xe2, 0x4e, 0x51, 0xae, 0xda, 0x76, 0x19, 0xda, 0xdb, 0xfc, 0xd5, 0x80, 0x47,
	0x6b, 0x69, 0xdc, 0x63, 0x16, 0xc6, 0xeb, 0xb3, 0x78, 0xac, 0x6d, 0x2f, 0xc8, 0x7c, 0xfc, 0xdf,
	0xb7, 0xe3, 0x83, 0xad, 0x76, 0x6c, 0xac, 0x61, 0x9e, 0xc5, 0xef, 0x06, 0x38, 0x2e, 0xc6, 0xfd,
	0xd4, 0x27, 0xf3, 0x78, 0x49, 0x54, 0x26, 0xf9, 0x60, 0x1c, 0x81, 0x35, 0x97, 0x86, 0x60, 0x75,
	0x8a, 0xf6, 0x94, 0xc1, 0xc3, 0xe8, 0x18, 0x40, 0x8f, 0x85, 0xf0, 0xaa, 0xa4, 0x2c, 0x6d, 0xf1,
	0xf0, 0xce, 0xa8, 0x98, 0x6f, 0x37, 0x2a, 0x3f, 0x80, 0x73, 0x41, 0xf8, 0x76, 0x7f, 0x54, 0x5a,
	0xf7, 0xfb, 0xf2, 0x1f, 0x06, 0x1c, 0x79, 0x8b, 0x25, 0xe5, 0xe4, 0xab, 0x94, 0x92, 0x05, 0x66,
	0x5b, 0xcb, 0xfa, 0xef, 0x6e, 0xc0, 0x9b, 0x92, 0x3f, 0x06, 0xb8, 0x96, 0xcf, 0x06, 0x14, 0x33,
	0xc7, 0x6c, 0x98, 0xc2, 0xad, 0x2c, 0x1e, 0x66, 0x4f, 0x3f, 0x81, 0x8a, 0xbe, 0xc7, 0xa8, 0xaa,
	0xc5, 0x61, 0xd7, 0x7e, 0x80, 0xf6, 0x61, 0xaf, 0xfb, 0xaa, 0xeb, 0x5f, 0xf5, 0x7b, 0x5d, 0xdb,
	0x40, 0x00, 0xe5, 0xc1, 0xe8, 0xec, 0xd2, 0x3b, 0xb7, 0x0b, 0x4f, 0x7b, 0x60, 0xad, 0xfe, 0x15,
	0x05, 0x67, 0xd4, 0xfb, 0xa6, 0xd7, 0xff, 0xb6, 0x67, 0x3f, 0x10, 0xca, 0x55, 0x7f, 0x34, 0x1c,
	0x9d, 0x09, 0x4a, 0x05, 0xcc, 0x91, 0xef, 0xd9, 0x05, 0x54, 0x03, 0x18, 0x78, 0xbe, 0x3b, 0xec,
	0x06, 0x67, 0xee, 0x95, 0x6d, 0x0a, 0xfd, 0xb2, 0x7f, 0xee, 0x5e, 0x06, 0x03, 0x77, 0xf8, 0xb5,
	0x5d, 0xec, 0xfc, 0x55, 0x84, 0x9a, 0xee, 0xc8, 0x4b, 0x92, 0x2e, 0xe9, 0x84, 0xa0, 0x53, 0x28,
	0xab, 0x86, 0xa1, 0xa6, 0xee, 0xc2, 0x6b, 0xfa, 0x57, 0xcf, 0xff, 0x00, 0x57, 0xd3, 0x3e, 0x80,
	0x87, 0x17, 0x84, 0xaf, 0xdf, 0x05, 0xd4, 0xd0, 0x98, 0x3b, 0x2f, 0x71, 0xfd, 0x68, 0x6d, 0x98,
	0x77, 0xce, 0xc9, 0x67, 0x00, 0xb7, 0xc3, 0x83, 0xb6, 0x16, 0xb0, 0x5e, 0xdf, 0xa5, 0xae, 0x98,
	0xa7, 0x70, 0xb0, 0x71, 0xa1, 0x51, 0xfe, 0xce, 0x3f, 0xdd, 0xed, 0xdd, 0x52, 0x3e, 0x87, 0x03,
	0xb5, 0x47, 0x39, 0xfd, 0xc9, 0xe6, 0xdb, 0x6b, 0x57, 0x77, 0x97, 0xfc, 0x1c, 0xaa, 0x5d, 0x4c,
	0xf9, 0xbb, 0x50, 0x4f, 0xc1, 0x72, 0x31, 0x56, 0x6b, 0x82, 0x4e, 0xf2, 0x51, 0xbc, 0x63, 0xad,
	0x77, 0xe9, 0x5f, 0xc2, 0xfe, 0x3a, 0xee, 0x1d, 0x22, 0x5c, 0xca, 0x8e, 0xeb, 0x3d, 0x5d, 0xf1,
	0xef, 0xda, 0xe0, 0xfa, 0xf1, 0x66, 0x6d, 0x5b, 0xf7, 0x6f, 0x5c, 0x96, 0xde, 0x4f, 0xff, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0x25, 0xbf, 0x76, 0x72, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TheaterServiceClient is the client API for TheaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TheaterServiceClient interface {
	Invite(ctx context.Context, in *InviteFriendsTheaterRequest, opts ...grpc.CallOption) (*Response, error)
	GetUserTheaters(ctx context.Context, in *GetAllUserTheatersRequest, opts ...grpc.CallOption) (*UserTheatersResponse, error)
	GetTheater(ctx context.Context, in *Theater, opts ...grpc.CallOption) (*UserTheaterResponse, error)
	CreateTheater(ctx context.Context, in *CreateTheaterRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveTheater(ctx context.Context, in *TheaterAuthRequest, opts ...grpc.CallOption) (*Response, error)
	EditTheater(ctx context.Context, in *TheaterAuthRequest, opts ...grpc.CallOption) (*Response, error)
	AddMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error)
	GetMembers(ctx context.Context, in *GetTheaterMembersRequest, opts ...grpc.CallOption) (*TheaterMembersResponse, error)
}

type theaterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTheaterServiceClient(cc grpc.ClientConnInterface) TheaterServiceClient {
	return &theaterServiceClient{cc}
}

func (c *theaterServiceClient) Invite(ctx context.Context, in *InviteFriendsTheaterRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/Invite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) GetUserTheaters(ctx context.Context, in *GetAllUserTheatersRequest, opts ...grpc.CallOption) (*UserTheatersResponse, error) {
	out := new(UserTheatersResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetUserTheaters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) GetTheater(ctx context.Context, in *Theater, opts ...grpc.CallOption) (*UserTheaterResponse, error) {
	out := new(UserTheaterResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) CreateTheater(ctx context.Context, in *CreateTheaterRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/CreateTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) RemoveTheater(ctx context.Context, in *TheaterAuthRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/RemoveTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) EditTheater(ctx context.Context, in *TheaterAuthRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/EditTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) AddMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) RemoveMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/RemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) GetMembers(ctx context.Context, in *GetTheaterMembersRequest, opts ...grpc.CallOption) (*TheaterMembersResponse, error) {
	out := new(TheaterMembersResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheaterServiceServer is the server API for TheaterService service.
type TheaterServiceServer interface {
	Invite(context.Context, *InviteFriendsTheaterRequest) (*Response, error)
	GetUserTheaters(context.Context, *GetAllUserTheatersRequest) (*UserTheatersResponse, error)
	GetTheater(context.Context, *Theater) (*UserTheaterResponse, error)
	CreateTheater(context.Context, *CreateTheaterRequest) (*Response, error)
	RemoveTheater(context.Context, *TheaterAuthRequest) (*Response, error)
	EditTheater(context.Context, *TheaterAuthRequest) (*Response, error)
	AddMember(context.Context, *AddOrRemoveMemberRequest) (*Response, error)
	RemoveMember(context.Context, *AddOrRemoveMemberRequest) (*Response, error)
	GetMembers(context.Context, *GetTheaterMembersRequest) (*TheaterMembersResponse, error)
}

// UnimplementedTheaterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTheaterServiceServer struct {
}

func (*UnimplementedTheaterServiceServer) Invite(ctx context.Context, req *InviteFriendsTheaterRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invite not implemented")
}
func (*UnimplementedTheaterServiceServer) GetUserTheaters(ctx context.Context, req *GetAllUserTheatersRequest) (*UserTheatersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTheaters not implemented")
}
func (*UnimplementedTheaterServiceServer) GetTheater(ctx context.Context, req *Theater) (*UserTheaterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) CreateTheater(ctx context.Context, req *CreateTheaterRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) RemoveTheater(ctx context.Context, req *TheaterAuthRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) EditTheater(ctx context.Context, req *TheaterAuthRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) AddMember(ctx context.Context, req *AddOrRemoveMemberRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedTheaterServiceServer) RemoveMember(ctx context.Context, req *AddOrRemoveMemberRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (*UnimplementedTheaterServiceServer) GetMembers(ctx context.Context, req *GetTheaterMembersRequest) (*TheaterMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembers not implemented")
}

func RegisterTheaterServiceServer(s *grpc.Server, srv TheaterServiceServer) {
	s.RegisterService(&_TheaterService_serviceDesc, srv)
}

func _TheaterService_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteFriendsTheaterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).Invite(ctx, req.(*InviteFriendsTheaterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_GetUserTheaters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserTheatersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetUserTheaters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetUserTheaters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetUserTheaters(ctx, req.(*GetAllUserTheatersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_GetTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Theater)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetTheater(ctx, req.(*Theater))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_CreateTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTheaterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).CreateTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/CreateTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).CreateTheater(ctx, req.(*CreateTheaterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_RemoveTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TheaterAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).RemoveTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/RemoveTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).RemoveTheater(ctx, req.(*TheaterAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_EditTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TheaterAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).EditTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/EditTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).EditTheater(ctx, req.(*TheaterAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrRemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).AddMember(ctx, req.(*AddOrRemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrRemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).RemoveMember(ctx, req.(*AddOrRemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheaterMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetMembers(ctx, req.(*GetTheaterMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TheaterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TheaterService",
	HandlerType: (*TheaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invite",
			Handler:    _TheaterService_Invite_Handler,
		},
		{
			MethodName: "GetUserTheaters",
			Handler:    _TheaterService_GetUserTheaters_Handler,
		},
		{
			MethodName: "GetTheater",
			Handler:    _TheaterService_GetTheater_Handler,
		},
		{
			MethodName: "CreateTheater",
			Handler:    _TheaterService_CreateTheater_Handler,
		},
		{
			MethodName: "RemoveTheater",
			Handler:    _TheaterService_RemoveTheater_Handler,
		},
		{
			MethodName: "EditTheater",
			Handler:    _TheaterService_EditTheater_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _TheaterService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _TheaterService_RemoveMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _TheaterService_GetMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "theater.proto",
}
