// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: ws.theater.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TheaterVideoPlayer_State int32

const (
	TheaterVideoPlayer_INVALID TheaterVideoPlayer_State = 0
	TheaterVideoPlayer_PLAYING TheaterVideoPlayer_State = 1
	TheaterVideoPlayer_PAUSED  TheaterVideoPlayer_State = 2
)

// Enum value maps for TheaterVideoPlayer_State.
var (
	TheaterVideoPlayer_State_name = map[int32]string{
		0: "INVALID",
		1: "PLAYING",
		2: "PAUSED",
	}
	TheaterVideoPlayer_State_value = map[string]int32{
		"INVALID": 0,
		"PLAYING": 1,
		"PAUSED":  2,
	}
)

func (x TheaterVideoPlayer_State) Enum() *TheaterVideoPlayer_State {
	p := new(TheaterVideoPlayer_State)
	*p = x
	return p
}

func (x TheaterVideoPlayer_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TheaterVideoPlayer_State) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_theater_proto_enumTypes[0].Descriptor()
}

func (TheaterVideoPlayer_State) Type() protoreflect.EnumType {
	return &file_ws_theater_proto_enumTypes[0]
}

func (x TheaterVideoPlayer_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TheaterVideoPlayer_State.Descriptor instead.
func (TheaterVideoPlayer_State) EnumDescriptor() ([]byte, []int) {
	return file_ws_theater_proto_rawDescGZIP(), []int{0, 0}
}

type TheaterVideoPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TheaterId   string                   `protobuf:"bytes,1,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	MediaSource *MediaSource             `protobuf:"bytes,2,opt,name=media_source,json=mediaSource,proto3" json:"media_source,omitempty"`
	CurrentTime float32                  `protobuf:"fixed32,4,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	State       TheaterVideoPlayer_State `protobuf:"varint,5,opt,name=state,proto3,enum=proto.TheaterVideoPlayer_State" json:"state,omitempty"`
	UserId      string                   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SentAt      *timestamp.Timestamp     `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
}

func (x *TheaterVideoPlayer) Reset() {
	*x = TheaterVideoPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ws_theater_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheaterVideoPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheaterVideoPlayer) ProtoMessage() {}

func (x *TheaterVideoPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_ws_theater_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheaterVideoPlayer.ProtoReflect.Descriptor instead.
func (*TheaterVideoPlayer) Descriptor() ([]byte, []int) {
	return file_ws_theater_proto_rawDescGZIP(), []int{0}
}

func (x *TheaterVideoPlayer) GetTheaterId() string {
	if x != nil {
		return x.TheaterId
	}
	return ""
}

func (x *TheaterVideoPlayer) GetMediaSource() *MediaSource {
	if x != nil {
		return x.MediaSource
	}
	return nil
}

func (x *TheaterVideoPlayer) GetCurrentTime() float32 {
	if x != nil {
		return x.CurrentTime
	}
	return 0
}

func (x *TheaterVideoPlayer) GetState() TheaterVideoPlayer_State {
	if x != nil {
		return x.State
	}
	return TheaterVideoPlayer_INVALID
}

func (x *TheaterVideoPlayer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TheaterVideoPlayer) GetSentAt() *timestamp.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_ws_theater_proto protoreflect.FileDescriptor

var file_ws_theater_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x73, 0x2e, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1,
	0x02, 0x0a, 0x12, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x68, 0x65, 0x61, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0b,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x74, 0x41, 0x74, 0x22, 0x2d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41,
	0x59, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x55, 0x53, 0x45, 0x44,
	0x10, 0x02, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ws_theater_proto_rawDescOnce sync.Once
	file_ws_theater_proto_rawDescData = file_ws_theater_proto_rawDesc
)

func file_ws_theater_proto_rawDescGZIP() []byte {
	file_ws_theater_proto_rawDescOnce.Do(func() {
		file_ws_theater_proto_rawDescData = protoimpl.X.CompressGZIP(file_ws_theater_proto_rawDescData)
	})
	return file_ws_theater_proto_rawDescData
}

var file_ws_theater_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ws_theater_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ws_theater_proto_goTypes = []interface{}{
	(TheaterVideoPlayer_State)(0), // 0: proto.TheaterVideoPlayer.State
	(*TheaterVideoPlayer)(nil),    // 1: proto.TheaterVideoPlayer
	(*MediaSource)(nil),           // 2: proto.MediaSource
	(*timestamp.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_ws_theater_proto_depIdxs = []int32{
	2, // 0: proto.TheaterVideoPlayer.media_source:type_name -> proto.MediaSource
	0, // 1: proto.TheaterVideoPlayer.state:type_name -> proto.TheaterVideoPlayer.State
	3, // 2: proto.TheaterVideoPlayer.sent_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ws_theater_proto_init() }
func file_ws_theater_proto_init() {
	if File_ws_theater_proto != nil {
		return
	}
	file_grpc_theater_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ws_theater_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheaterVideoPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ws_theater_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_theater_proto_goTypes,
		DependencyIndexes: file_ws_theater_proto_depIdxs,
		EnumInfos:         file_ws_theater_proto_enumTypes,
		MessageInfos:      file_ws_theater_proto_msgTypes,
	}.Build()
	File_ws_theater_proto = out.File
	file_ws_theater_proto_rawDesc = nil
	file_ws_theater_proto_goTypes = nil
	file_ws_theater_proto_depIdxs = nil
}
